# Generated by Django 5.2.4 on 2025-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="libro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "imagen",
                    models.ImageField(
                        null=True, upload_to="imagenes/", verbose_name="Imagen"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(null=True, verbose_name="Descripcion"),
                ),
            ],
        ),
    ]
